= Introduction
Petar Tahchiev
:doctype: book
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: coderay
:icons: font
:last-update-label!:

The nemesis platform bom (Bill Of Materials) specifies all the dependencies for the platform. It inherits the link:http://docs.spring.io/platform/docs/1.1.2.RELEASE/reference/htmlsingle/[spring platform bom version 1.2.2.RELEASE] and includes
also the  link:http://repo1.maven.org/maven2/org/drools/drools-bom/[drools maven bom]. On top of that it includes some more third party dependencies, which are not part of the other boms. The version of the deendencies is extracted as a property for easy management, and the dependencies themseves are specified as managed dependencies
so that the end-user can declare them without version.

== List of dependencies
For a complete list of dependencies please have a look inside the `pom.xml`.

== Release cycle
A new version of the platform bom is released with each new version of the nemesis platform. Thus we make sure that the dependencies are compatible with each other.
