= Project plan for a sample nemesis project
Petar Tahchiev
:doctype: book
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlight.js
:icons: font
:last-update-label!:

This is a short guide to help you structure and estimate your project. It gives a sample project plan with some guidelines on what to look when implementing a new project using the Nemesis Platform.

== Requirements gathering.
Before you begin, you have to make sure you understand the requirements of the client. 

=== Design understanding and cms
Make sure you work together with the client and their designer to understand how many areas of the website they would like to be editable in the future. Please follow our link:/current/platform/modules/nemesis-module-cms/index.html[cms guide^] when guiding the client on chosing page templates, creating pages, and defining different widgets on their website.

== Project setup.
In the beginning you need to define how many developers will be needed on the project. Our recommendation is, depending on the complexity of the project, a team of three senior java developers and project manager. A very good understanding of link:https://spring.io[Spring framework^] is needed, as well as link:https://cloud.spring.io/[cloud deployments^].

=== Onboarding
Setup a source-control system and a continous integration system to execute your tests. Make sure you all follow the same code formatting style to make development easier. We provide our code-formatting guidelines in the link:/current/platform/getting-started.html[onboarding guideliness^] but you can easily use ones of your own. Also make sure to follow the link:getting-started.html[getting-started guide^].

=== Initial project setup
You can use the link:https://start.nemesis.io/[nemesis initializer^] (documentation is link:/current/b2c/getting-started.html[here^]) to create a sample project. The project will be generated in less than 5 minutes and will setup 3 stores for you - a sample CMS website (named nemesis), a sample B2C website (named solarapparel) and a sample B2B website (named polarapparel). Ones the project is setup you can commit it to the git source control to be used by all other developers in the team.

== Development
=== Import client's data
Whether you are creating a new project from scratch or you are migrating an existing website to the Nemesis Platform you will need to import client's data. You first need to delete the sample data that comes with the platform, and then ask the client to provide their data in csv files following our link:html.html[csv documentation^]. 

=== Implementation of changes
Once you have gathered all the requirements from the client, make sure you pin-point the differences from the out-of-the-box platform behaviour. All the changes need to be implemented.
The following changes need to be taken in account:

[cols="<,<"]
|===
|JSP|Look-and-feel with need to be customized for every different client
|Custom themes| It's a good idea to organize all the css and javascript files in a custom theme module. This way the default theme on the website can be changed without redeploy.
|CMS slots| Slots need to be implemented on the jsps to allow substitution of widgets in those slots.
|===

=== Implementation of new features
New features and modules are discussed with the client and estemated separately.

=== Integration with other third-party systems
You will for sure need to integrate with different services when developing your website. The basic four are listed below:
[cols="<,<"]
|===
|Payment|The nemesis payment platform provides numerous link:index.html[payment modules^] to chose from. However if you don't want to use them, or your payment provider is not listed, you will need to write your own implementation.
|Delivery|You can pick from some of the link:index.html[already provided delivery modules^] or if your delivery provider is not listed you will have to implement your own integration.
|===

Additionally there are some more integrations that might need to be implemented. Optional integrations are:
[cols="<,<"]
|===
|Warehouse|A mock implementation is provided to allow you to send/receive consignment information to/from the warehouse. Depending on the software that is chosen you will need to create a custom integration with the warehouse.
|Fraud|Integration with a custom fraud-detection service for the payment processing. Check the existing link:index.html[fraud-detection modules], before you implement your own.
|Address verification|Integration with address verification services. The nemesis platform has some link:index.html[address verfication modules].
|Custom integrations|Any custom integration that the client requests.
|===

=== Implementation of tests
You need to also plan some time for development of tests for your project. Even though every nemesis project comes bundled with more than 400 tests, over the course of the project these tests will start failing, so there needs to be some time to rework them to fit the changed requirements.
