= Performing a release
Petar Tahchiev
:doctype: book
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: coderay
:icons: font
:last-update-label!:

To perform a release of the different Nemesis projects follow the steps below.

WARNING: Make sure the CI build is green and you have no snapshot dependencies

== Release the Platform BOM
Here are the steps to follow if you want to release the platform BOM

 * Before release change the value of the `nemesis.version` property in the `pom.xml`
 * The commands for the release are the following
[source,bash]
----
 mvn release:clean
 mvn release:prepare -Dtag=0.8 -DreleaseVersion=0.8 -DdevelopmentVersion=0.9-SNAPSHOT
 mvn release:perform
----
 * Deploy the bom with the new snapshot version to the maven repository so that we can use it.
[source,bash]
----
mvn deploy
----
 
== Release the platform project
To release the nemesis-platform issue the same commands as above:
[source,bash]
----
mvn release:clean
mvn release:prepare -Dtag=0.8 -DreleaseVersion=0.8 -DdevelopmentVersion=0.9-SNAPSHOT
----
This will create a tag with the name specified in the github repository. You will be asked several times for your github username and password. To avoid the repetitive work of filling you username and password define the following server in your settings.xml:
[source,xml]
----
<server>
   <id>githhub</id>
   <username>YOUR_USERNAME</username>
   <password>YOUR_PASSWORD</password>
</server>
----

You will need to resolve the parent bom - resolve it to just released version and set the development version - the one you just specified)
[source,bash]
----
mvn release:perform -Dmaven.javadoc.skip=true
----
The release perform will actually clone the created tag, make a jar and install it in the link:https://repository.nemesis.io/artifactory/ext-release-local/[official nemesis release repository^].

NOTE: This command might take some time as it tries to clone the tag that it created from the git repository and the platform project is quite big. 

Finally you need to issue:
[source,bash]
----
mvn deploy
----
to deploy the jars to the reposotory and rebuild without cache the circleci

== Release the tools
To release the tools follow the same commands as above. Also after the release don't forget to upload the jars to the maven repository because the nemesis archetype is 
depending on it.

== Release the themes
To release the themes follow the same commands as above. Also after the release don't forget to upload the jars to the maven repository because the nemesis archetype is 
depending on them.

== Release the archetype
The nemesis-archetype can be released with the above commands. It will take some time to resolve all the module versions so be patient. At the end, when you
issue the `mvn release:perform` command maven will try to upload the war file to the nemesis-repository. We don't need that war file there (as it is too big)
so you can cancel the upload and simply issue `mvn release:clean` to clean the release. After that you have to do the following:
[source,bash]
----
git checkout tags/0.7
----
This will checkout the released tag version.
[source,bash]
----
mvn clean install
----
This will build the tag version.
[source,bash]
----
mvn archetype:create-from-project -Darchetype.properties=src/main/resources/archetype.properties -s src/main/resources/settings.xml
----
This will create archetype from the given project.
[source,bash]
----
mvn package deploy -f target/generated-sources/archetype/ -s src/main/resources/settings.xml
----
This will build and deploy the archetype with version 0.7 to the nemesis-repository so that orther clients can create projects from it.

== Release the consoles
Release the nemesis-consoles project with the above commands. 

== Make sure the CI build is green again.
Next step is to make sure the link:http://circleci.com/[CircleCI] build is stable again.

== Generate a changelog	
Go though each module and generate a changelog for what was changed in this version. We use the link:https://skywinder.github.io/github-changelog-generator/[github_changelog_generator] tool for generating the changelog.
Simply run the following command in each of the released modules and then push the new changelog:
[source,bash]
----
github_changelog_generator
----

== Update your IDE
Make sure your IDE has the right `since` attribute. You should bump the version so that every new class that you create will have the correct version on it.
For IntellijIDEA you can do that in  `File` -> `Settings` -> `Editor` -> `File and code templates` and click on the `Includes` tab .

== Update version in start.nemesis.io
You will need to update the versions in the `nemesis-start` project to reflect the newly released version.

== Make new alias on the documentation website
You need to make the alias `current` to point to the latest version that you just released. Also renamed the old `0.8-SNAPSHOT` version to be the just `0.8` as there will be no more deployments in that version.
[source,bash]
----
unlink current
unlink current-snapshot
ln -s 0.9 current
ln -s 1.0-SNAPSHOT current-snapshot
----
